# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/Gen

language: julia
julia:
  - 1.5

# run these in parallel
env:
  - GEN_EXAMPLE=gp_structure GKS_ENCODING="utf8" GKSwstype="100"
  - GEN_EXAMPLE=regression
  - GEN_EXAMPLE=involutive_mcmc
  - GEN_EXAMPLE=decode
  - GEN_EXAMPLE=mle
  - GEN_EXAMPLE=coal

script: "JULIA_PROJECT=${GEN_EXAMPLE} ./${GEN_EXAMPLE}/run.sh"
