# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/Gen

language: julia
julia:
  - 1.5

jobs:
  include:

    # different versions of bayesian polynomial regression
    - stage: regression
      script:
        - julia --project=regression -e 'using Pkg; Pkg.update(); include("regression/run_all.jl")'

    # Gaussian process structure inference
    - stage: gp_structure
      script:
        - julia --project=gp_structure -e 'using Pkg; Pkg.update(); include("gp_structure/run_all.jl")'

    # involutive MCMC minimal example
    - stage: involutive_mcmc
      script:
        - julia --project=involutive_mcmc -e 'using Pkg; Pkg.update(); include("involutive_mcmc/run_all.jl")'
