# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/Gen

language: julia
julia:
  - 1.5

# run these in parallel
env:
  - GEN_EXAMPLE=regression
  - GEN_EXAMPLE=gp_structure
  - GEN_EXAMPLE=involutive_mcmc
  - GEN_EXAMPLE=decode
  - GEN_EXAMPLE=mle
  - GEN_EXAMPLE=coal

# different versions of bayesian polynomial regression
# Gaussian process structure inference
# involutive MCMC minimal example
# decoding substitution cipher using bigram model

script: JULIA_PROJECT=$GEN_EXAMPLE julia -e 'using Pkg; Pkg.update(); include("$(ENV["GEN_EXAMPLE"])/run_all.jl")'
